from dotenv import load_dotenv
import os

load_dotenv()

CROWDSTRIKE_CLIENT_ID = os.getenv("CROWDSTRIKE_CLIENT_ID")
CROWDSTRIKE_SECRET = os.getenv("CROWDSTRIKE_SECRET")
CROWDSTRIKE_BASE_URL = os.getenv("CROWDSTRIKE_BASE_URL")
CROWDSTRIKE_VULNERABILITY_FILTER = os.getenv("CROWDSTRIKE_VULNERABILITY_FILTER")

ABNORMAL_API_KEY = os.getenv("ABNORMAL_API_KEY")

# DELINEA_API_KEY = os.getenv("DELINEA_API_KEY")

BITSIGHT_API_KEY = os.getenv("BITSIGHT_API_KEY")

# TENABLE_API_KEY = os.getenv("TENABLE_API_KEY")
